apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: activator-service
  namespace: kourier-system
spec:
  host: activator-service.knative-serving.svc.cluster.local
  # host: hello.default.svc.cluster.local
  subsets:
  - name: activator-cloud
    labels:
      app: activator
      bonaregion: cloud
  - name: activator-edge
    labels:
      app: activator
      bonaregion: edge
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activator-service
  namespace: kourier-system
spec:
  hosts:
  # - activator-service.knative-serving.svc.cluster.local
  - hello.default.svc.cluster.local
  http:
  - match:
    - headers:
        bonaregion:
          exact: cloud
    route:
    - destination:
        host: activator-service.knative-serving.svc.cluster.local
        subset: activator-cloud
  - match:
    - headers:
        bonaregion:
          exact: edge
    route:
    - destination:
        host: activator-service.knative-serving.svc.cluster.local
        subset: activator-edge
---